services:
  backend:
    build:
      context: ../../../../backend
      dockerfile: Dockerfile.ec2
    container_name: todo_backend
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"
